apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
        - name: angular-frontend
          image: my-angular-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4200

---
apiVersion: v1
kind: Service
metadata:
  name: angular-frontend
spec:
  type: NodePort
  ports:
    - port: 4200
      targetPort: 4200
      nodePort: 30000
  selector:
    app: angular-frontend
