apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: my-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8091
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/rental_car_db
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8091
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 8091
      targetPort: 8091
      nodePort: 32091
